import React,{useEffect,useMemo,useState}from'react';import{Project,PocketBandState,RollDivision}from'../types/daw';import{AudioEngine}from'../audio/AudioEngine';import{DrumBrowser}from'./DrumBrowser';import{activePattern,duplicatePattern,makePocketBand,resizePattern,velocity}from'../pocketband/PocketBandEngine';
type Props={project:Project;onUpdateProject:(u:(p:Project)=>Project,d?:string)=>void;currentBeat:number};
export const BeatPadView:React.FC<Props>=({project,onUpdateProject,currentBeat})=>{const engine=AudioEngine.getInstance();const pb=project.pocketBand||makePocketBand();const [selected,setSelected]=useState(0);const [browser,setBrowser]=useState(false);const pattern=activePattern(pb);const offset=pb.bank*16;const pads=useMemo(()=>pb.pads.slice(offset,offset+16),[pb,offset]);const step=Math.floor(currentBeat*4)%pattern.stepCount;
const update=(fn:(s:PocketBandState)=>PocketBandState,label:string)=>onUpdateProject(p=>({...p,pocketBand:fn(p.pocketBand||makePocketBand())}),label);
const patchPad=(patch:any)=>update(s=>({...s,pads:s.pads.map(p=>p.index===offset+selected?{...p,...patch}:p)}),'Edit pad');
const hit=async(i:number,pressure=1)=>{const pad=pads[i],v=velocity(Math.round(pressure*127),pad.velocityCurve,pad.fixedVelocity);await engine.playPocketPad(pad,v/127);if(pb.noteRepeat)engine.schedulePocketRoll(pad,v/127,pb.roll,.5);update(s=>{const p=activePattern(s);return{...s,patterns:s.patterns.map(x=>x.id!==p.id?x:{...p,tracks:p.tracks.map(t=>t.padIndex!==pad.index? t:{...t,steps:t.steps.map((q,n)=>n===step?{...q,active:true,velocity:v}:q)})})}}},'BeatPad hit')};
const selectedPad=pads[selected];const rolls:RollDivision[]=['1/4','1/8','1/16','1/32','1/64'];
useEffect(()=>engine.onPocketMidi((note,v)=>{const i=pads.findIndex(p=>p.note===note);if(i>=0)hit(i,v/127)}),[pads,step,engine]);
useEffect(()=>{const h=(e:KeyboardEvent)=>{const keys='1234qwerasdfzxcv';const i=keys.indexOf(e.key.toLowerCase());if(i>=0)hit(i,e.repeat?.7:1)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[pads,step]);
return <div className="flex-1 bg-neutral-950 p-3 flex flex-col gap-3 overflow-auto"><div className="flex flex-wrap gap-2 items-center"><b className="text-xl tracking-widest mr-auto">POCKETBAND <span className="text-rose-400">DRUM MACHINE</span></b>{[0,1,2,3].map(b=><button onClick={()=>update(s=>({...s,bank:b}),'Bank')} className={'px-3 py-2 rounded '+(pb.bank===b?'bg-rose-600':'bg-neutral-800')}>BANK {String.fromCharCode(65+b)}</button>)}<select value={pb.roll} onChange={e=>update(s=>({...s,roll:e.target.value as RollDivision}),'Roll')} className="bg-neutral-900 p-2 rounded">{rolls.map(x=><option>{x} ROLL</option>)}</select><button onClick={()=>update(s=>({...s,noteRepeat:!s.noteRepeat}),'Note repeat')} className={pb.noteRepeat?'bg-cyan-600 p-2 rounded':'bg-neutral-800 p-2 rounded'}>NOTE REPEAT</button></div>
<div className="grid grid-cols-4 gap-2 min-h-[360px]">{pads.map((p,i)=><button key={p.index} onPointerDown={e=>{setSelected(i);hit(i,Math.max(.15,Math.min(1,(e.nativeEvent as any).pressure||1)))}} style={{borderColor:p.color,boxShadow:selected===i?'0 0 18px '+p.color:undefined}} className="rounded-xl border-2 bg-neutral-900 active:scale-[.98] p-3 text-left"><small>PAD {p.index+1} • CHOKE {p.chokeGroup||'-'}</small><div className="font-black">{p.name}</div><div className="text-xs text-neutral-500 truncate">{p.sampleId}</div><div className="text-xs">{p.pitch>0?'+':''}{p.pitch} st • {p.velocityCurve}</div></button>)}</div>
<div className="grid grid-cols-2 lg:grid-cols-4 gap-2 bg-neutral-900 p-3 rounded-xl"><label>SAMPLE<div><button className="bg-rose-700 px-3 py-2 rounded" onClick={()=>setBrowser(true)}>DRUM BROWSER</button></div></label><label>COLOR<input type="color" value={selectedPad.color} onChange={e=>patchPad({color:e.target.value})}/></label><label>CHOP START<input type="range" min="0" max="1" step=".01" value={selectedPad.chopStart} onChange={e=>patchPad({chopStart:+e.target.value})}/></label><label>CHOP END<input type="range" min="0" max="1" step=".01" value={selectedPad.chopEnd} onChange={e=>patchPad({chopEnd:+e.target.value})}/></label><label>TUNE {selectedPad.pitch}<input type="range" min="-24" max="24" value={selectedPad.pitch} onChange={e=>patchPad({pitch:+e.target.value})}/></label><label>CHOKE<input type="number" min="0" max="8" value={selectedPad.chokeGroup} onChange={e=>patchPad({chokeGroup:+e.target.value})}/></label><label>VELOCITY<select value={selectedPad.velocityCurve} onChange={e=>patchPad({velocityCurve:e.target.value})} className="bg-neutral-800 ml-2"><option>linear</option><option>soft</option><option>hard</option><option>fixed</option></select></label><label>FILTER {selectedPad.fx.filterHz}<input type="range" min="80" max="20000" value={selectedPad.fx.filterHz} onChange={e=>patchPad({fx:{...selectedPad.fx,filterHz:+e.target.value}})}/></label></div>
<div className="flex flex-wrap gap-2 items-center"><b>{pattern.name}</b><button onClick={()=>update(s=>({...s,patterns:[...s.patterns,duplicatePattern(pattern)]}),'Duplicate pattern')}>DUPLICATE</button>{([16,32,64] as const).map(n=><button onClick={()=>update(s=>({...s,patterns:s.patterns.map(p=>p.id===pattern.id?resizePattern(p,n):p)}),'Step length')} className={pattern.stepCount===n?'text-rose-400':''}>{n} STEPS</button>)}<label>SWING {pattern.swing}<input type="range" min="0" max="75" value={pattern.swing} onChange={e=>update(s=>({...s,patterns:s.patterns.map(p=>p.id===pattern.id?{...p,swing:+e.target.value}:p)}),'Swing')}/></label><button onClick={()=>update(s=>({...s,chain:[...s.chain,pattern.id]}),'Chain')}>ADD TO CHAIN</button><span>CHAIN {pb.chain.length} • SCENES {pb.scenes.length} • STEP {step+1}</span></div>{browser&&<DrumBrowser pad={selectedPad} onClose={()=>setBrowser(false)} onAssign={x=>{patchPad({name:x.name,sampleId:x.id,sampleUrl:x.url});setBrowser(false)}}/>}</div>};